# Generated by Django 5.2.2 on 2025-06-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
    ]
