# Generated by Django 5.2.2 on 2025-06-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
