# Generated by Django 5.2.1 on 2025-05-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aty', models.CharField(max_length=30)),
                ('fam', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tuulgan_kunu', models.DateField()),
            ],
        ),
    ]
