# Generated by Django 5.2.1 on 2025-05-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('first_name', models.CharField(db_column='Name', max_length=30, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('tuulgan_kun', models.DateField()),
            ],
        ),
    ]
